spring:
  r2dbc:
    datasource:
      host: localhost
      port: 3306
      database:
      username:
      password:
      driverClassName: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 10
      max-lifetime: 1800000 #1800000
      connection-timeout: 30000 #30000
      validation-timeout: 5000
      #connection-test-query: SELECT 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
